import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const LANGUAGES = [
  { code: 'en', label: 'English', native: 'English' },
  { code: 'hi', label: 'Hindi', native: 'हिंदी' },
  { code: 'pb', label: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
  { code: 'mr', label: 'Marathi', native: 'मराठी' },
  { code: 'te', label: 'Telugu', native: 'తెలుగు' },
];

export const TRANSLATIONS = {
  en: {
    brand_title: 'KisanSetu',
    brand_tagline: 'Smart Agricultural Procurement & Queue System',
    brand_badge: 'MANDI PORTAL',
    nav_home: 'Home',
    nav_book_slot: 'Book Slot',
    nav_my_tokens: 'My Passes',
    nav_mandi_queue: 'Mandi Live Queue',
    nav_display_screen: 'Public Mandi TV',
    nav_analytics: 'Analytics',
    nav_admin_panel: 'Super Admin',
    nav_officer_portal: 'Officer Portal',
    nav_profile: 'My Profile',
    nav_login: 'Login / Sign In',
    nav_logout: 'Logout',
    cta_book_now: 'Book Procurement Slot',
    cta_check_token: 'Track Live Token',
    cta_ai_help: 'AI Voice Assistant',
    hero_title: 'Zero Waiting Time. Guaranteed MSP Procurement.',
    hero_subtitle: 'Smart slot reservation and live transparent queue management for Indian farmers at Government Mandis.',
    live_msp_rates: 'Today Official MSP Rates',
    quintal: 'Quintal',
    per_quintal: 'per Quintal',
    price_trends_title: 'Commodity Price Trend & MSP Comparison',
    price_trends_subtitle: '7-Day APMC Market Movement vs Statutory MSP Benchmark',
    mandi_market_rate: 'Current Mandi Rate',
    govt_msp_floor: 'Govt MSP Floor',
    net_premium: 'Farmer Premium',
    weekly_range: '7-Day Range',
    msp_assured_badge: '100% MSP Assured',
    benchmark_feed: 'Benchmark APMC Mandi Feed',
    status_booked: 'Booked',
    status_checked_in: 'At Mandi Gate',
    status_called: 'Called to Bay',
    status_quality: 'Quality Testing',
    status_weighing: 'Weighbridge',
    status_unloading: 'Unloading Bay',
    status_procured: 'Procured & J-Form Ready',
    step_crop_details: '1. Crop Details',
    step_centre_select: '2. Select Mandi Centre',
    step_slot_time: '3. Pick Date & Time Slot',
    btn_confirm_booking: 'Confirm Slot Reservation',
    btn_call_next: 'Call Next Vehicle',
    btn_check_in: 'Gate Check-in',
    token_label: 'Token No.',
    wait_time_label: 'Estimated Turnaround Time',
    vehicles_ahead: 'Vehicles Ahead in Queue',
  },
  hi: {
    brand_title: 'किसान सेतु',
    brand_tagline: 'कृषि खरीद स्लॉट एवं लाइव कतार प्रबंधन प्रणाली',
    brand_badge: 'मंडी पोर्टल',
    nav_home: 'मुख्य पृष्ठ',
    nav_book_slot: 'स्लॉट बुक करें',
    nav_my_tokens: 'मेरे टोकन पास',
    nav_mandi_queue: 'मंडी लाइव कतार',
    nav_display_screen: 'मंडी टीवी स्क्रीन',
    nav_analytics: 'एनालिटिक्स',
    nav_admin_panel: 'सुपर एडमिन',
    nav_officer_portal: 'अधिकारी पोर्टल',
    nav_profile: 'मेरी प्रोफाइल',
    nav_login: 'लॉग इन करें',
    nav_logout: 'लॉग आउट',
    cta_book_now: 'फसल खरीद स्लॉट बुक करें',
    cta_check_token: 'लाइव टोकन ट्रैक करें',
    cta_ai_help: 'एआई वॉयस सहायक',
    hero_title: 'बिना कतार, समय पर फसल खरीद। पक्का एमएसपी भुगतान।',
    hero_subtitle: 'सरकारी मंडियों में किसानों के लिए स्मार्ट स्लॉट आरक्षण और पारदर्शी लाइव कतार ट्रैकिंग व्यवस्था।',
    live_msp_rates: 'आज का सरकारी एमएसपी (MSP) भाव',
    quintal: 'क्विंटल',
    per_quintal: 'प्रति क्विंटल',
    price_trends_title: 'फसल भाव रुझान एवं एमएसपी तुलना',
    price_trends_subtitle: '7-दिवसीय मंडी भाव एवं सरकारी न्यूनतम समर्थन मूल्य',
    mandi_market_rate: 'वर्तमान मंडी भाव',
    govt_msp_floor: 'सरकारी एमएसपी फ्लोर',
    net_premium: 'किसान प्रीमियम',
    weekly_range: '7-दिवसीय भाव दायरा',
    msp_assured_badge: '100% एमएसपी गारंटी',
    benchmark_feed: 'प्रामाणिक एपीएमसी मंडी डेटा',
    status_booked: 'स्लॉट बुक',
    status_checked_in: 'मंडी गेट पर उपस्थित',
    status_called: 'काउंटर पर बुलाया गया',
    status_quality: 'गुणवत्ता जांच जारी',
    status_weighing: 'धर्मकांटा वजन',
    status_unloading: 'अनलोडिंग शेड',
    status_procured: 'खरीद पूर्ण एवं जे-फॉर्म तैयार',
    step_crop_details: '1. फसल और मात्रा का विवरण',
    step_centre_select: '2. खरीद केंद्र का चयन',
    step_slot_time: '3. तारीख और समय स्लॉट',
    btn_confirm_booking: 'स्लॉट बुकिंग पक्की करें',
    btn_call_next: 'अगला वाहन बुलाएं',
    btn_check_in: 'गेट चेक-इन करें',
    token_label: 'टोकन संख्या',
    wait_time_label: 'अनुमानित प्रतीक्षा समय',
    vehicles_ahead: 'कतार में आगे वाहन',
  },
  pb: {
    brand_title: 'ਕਿਸਾਨ ਸੇਤੂ',
    brand_tagline: 'ਸਮਾਰਟ ਖਰੀਦ ਸਲਾਟ ਅਤੇ ਲਾਈਵ ਕਤਾਰ ਪ੍ਰਬੰਧਨ',
    brand_badge: 'ਮੰਡੀ ਪੋਰਟਲ',
    nav_home: 'ਮੁੱਖ ਪੰਨਾ',
    nav_book_slot: 'ਸਲਾਟ ਬੁੱਕ ਕਰੋ',
    nav_my_tokens: 'ਮੇਰੇ ਟੋਕਨ',
    nav_mandi_queue: 'ਮੰਡੀ ਲਾਈਵ ਕਤਾਰ',
    nav_display_screen: 'ਮੰਡੀ ਟੀਵੀ ਸਕ੍ਰੀਨ',
    nav_analytics: 'ਵਿਸ਼ਲੇਸ਼ਣ',
    nav_admin_panel: 'ਸੁਪਰ ਐਡਮਿਨ',
    nav_officer_portal: 'ਅਧਿਕਾਰੀ ਡੈਸ਼ਬੋਰਡ',
    nav_profile: 'ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ',
    nav_login: 'ਲਾਗਇਨ',
    nav_logout: 'ਲਾਗਆਉਟ',
    cta_book_now: 'ਖਰੀਦ ਸਲਾਟ ਬੁੱਕ ਕਰੋ',
    cta_check_token: 'ਲਾਈਵ ਟੋਕਨ ਦੇਖੋ',
    cta_ai_help: 'ਏਆਈ ਆਵਾਜ਼ ਸਹਾਇਕ',
    hero_title: 'ਬਿਨਾਂ ਲੰਬੀ ਉਡੀਕ, ਸਿੱਧੀ ਮੰਡੀ ਖਰੀਦ।',
    hero_subtitle: 'ਪੰਜਾਬ ਅਤੇ ਹਰਿਆਣਾ ਦੇ ਕਿਸਾਨਾਂ ਲਈ ਪਾਰਦਰਸ਼ੀ ਮੰਡੀ ਸਲਾਟ ਬੁਕਿੰਗ ਅਤੇ ਲਾਈਵ ਕਤਾਰ ਸਿਸਟਮ।',
    live_msp_rates: 'ਅੱਜ ਦੇ ਸਰਕਾਰੀ ਐਮਐਸਪੀ (MSP) ਰੇਟ',
    quintal: 'ਕੁਇੰਟਲ',
    per_quintal: 'ਪ੍ਰਤੀ ਕੁਇੰਟਲ',
    price_trends_title: 'ਫਸਲ ਕੀਮਤ ਰੁਝਾਨ ਅਤੇ ਐਮਐਸਪੀ ਤੁਲਨਾ',
    price_trends_subtitle: '7-ਦਿਨਾ ਮੰਡੀ ਕੀਮਤਾਂ ਅਤੇ ਸਰਕਾਰੀ ਐਮਐਸਪੀ ਬੈਂਚਮਾਰਕ',
    mandi_market_rate: 'ਮੌਜੂਦਾ ਮੰਡੀ ਰੇਟ',
    govt_msp_floor: 'ਸਰਕਾਰੀ ਐਮਐਸਪੀ',
    net_premium: 'ਕਿਸਾਨ ਪ੍ਰੀਮੀਅਮ',
    weekly_range: '7-ਦਿਨਾਂ ਦਾ ਘੇਰਾ',
    msp_assured_badge: '100% ਐਮਐਸਪੀ ਗਾਰੰਟੀ',
    benchmark_feed: 'ਪ੍ਰਮਾਣਿਤ ਏਪੀਐਮਸੀ ਮੰਡੀ ਫੀਡ',
    status_booked: 'ਸਲਾਟ ਬੁੱਕ',
    status_checked_in: 'ਗੇਟ ਤੇ ਪਹੁੰਚ ਗਏ',
    status_called: 'ਅੱਗੇ ਬੁਲਾਇਆ ਗਿਆ',
    status_quality: 'ਕੁਆਲਿਟੀ ਜਾਂਚ',
    status_weighing: 'ਕੰਡਾ ਵਜ਼ਨ',
    status_unloading: 'ਖਾਲੀ ਕਰਨ ਵਾਲੀ ਥਾਂ',
    status_procured: 'ਖਰੀਦ ਮੁਕੰਮਲ ਅਤੇ ਜੇ-ਫਾਰਮ ਤਿਆਰ',
    step_crop_details: '1. ਫਸਲ ਦਾ ਵੇਰਵਾ',
    step_centre_select: '2. ਮੰਡੀ ਚੁਣੋ',
    step_slot_time: '3. ਸਮਾਂ ਸਲਾਟ',
    btn_confirm_booking: 'ਸਲਾਟ ਪੱਕਾ ਕਰੋ',
    btn_call_next: 'ਅਗਲਾ ਟਰਾਲੀ ਬੁਲਾਓ',
    btn_check_in: 'ਗੇਟ ਐਂਟਰੀ ਕਰੋ',
    token_label: 'ਟੋਕਨ ਨੰਬਰ',
    wait_time_label: 'ਅੰਦਾਜ਼ਨ ਸਮਾਂ',
    vehicles_ahead: 'ਤੁਹਾਡੇ ਤੋਂ ਅੱਗੇ ਵਾਹਨ',
  },
  mr: {
    brand_title: 'किसान सेतू',
    brand_tagline: 'शेतकरी खरेदी स्लॉट आणि रांग व्यवस्थापन',
    brand_badge: 'मार्केट पोर्टल',
    nav_home: 'मुख्यपृष्ठ',
    nav_book_slot: 'स्लॉट बुक करा',
    nav_my_tokens: 'माझे पास',
    nav_mandi_queue: 'मार्केट रांग',
    nav_display_screen: 'मार्केट टीव्ही स्क्रीन',
    nav_analytics: 'विश्लेषण',
    nav_admin_panel: 'सुपर ॲडमिन',
    nav_officer_portal: 'अधिकारी पोर्टल',
    nav_profile: 'माझे प्रोफाईल',
    nav_login: 'लॉगिन करा',
    nav_logout: 'लॉगआउट',
    cta_book_now: 'खरेदी स्लॉट बुक करा',
    cta_check_token: 'थेट टोकन ट्रॅक करा',
    cta_ai_help: 'एआय सहाय्यक',
    hero_title: 'रांगेत वेळ वाया न घालवता हमीभाव खरेदी.',
    hero_subtitle: 'शेतकऱ्यांसाठी आधुनिक आणि पारदर्शक स्लॉट बुकिंग प्रणाली.',
    live_msp_rates: 'आजचे अधिकृत हमीभाव (MSP)',
    quintal: 'क्विंटल',
    per_quintal: 'प्रति क्विंटल',
    price_trends_title: 'बाजारभाव ट्रेंड आणि हमीभाव (MSP) तुलना',
    price_trends_subtitle: '७-दिवसीय कृषी उत्पन्न बाजार समिती आणि अधिकृत हमीभाव',
    mandi_market_rate: 'सध्याचा बाजारभाव',
    govt_msp_floor: 'शासकीय हमीभाव (MSP)',
    net_premium: 'शेतकरी नफा',
    weekly_range: '७-दिवसीय भाव मर्यादा',
    msp_assured_badge: '१००% हमीभाव खात्री',
    benchmark_feed: 'अधिकृत एपीएमसी बाजार फीड',
    status_booked: 'बुक झाले',
    status_checked_in: 'गेटवर हजर',
    status_called: 'बोलावले',
    status_quality: 'गुणवत्ता तपासणी',
    status_weighing: 'वजन काटा',
    status_unloading: 'अनलोडिंग',
    status_procured: 'खरेदी पूर्ण व पावती तयार',
    step_crop_details: '१. पीक तपशील',
    step_centre_select: '२. खरेदी केंद्र निवडा',
    step_slot_time: '३. वेळ स्लॉट निवडा',
    btn_confirm_booking: 'स्लॉट निश्चित करा',
    btn_call_next: 'पुढील वाहन बोलवा',
    btn_check_in: 'गेटवर नोंदणी करा',
    token_label: 'टोकन क्र.',
    wait_time_label: 'अंदाजे वेळ',
    vehicles_ahead: 'रांगेत पुढे असलेली वाहने',
  },
  te: {
    brand_title: 'కిసాన్ సేతు',
    brand_tagline: 'వ్యవసాయ సేకరణ స్లాట్ & క్యూ నిర్వహణ',
    brand_badge: 'మండీ పోర్టల్',
    nav_home: 'హోమ్',
    nav_book_slot: 'స్లాట్ బుక్ చేయండి',
    nav_my_tokens: 'నా పాస్‌లు',
    nav_mandi_queue: 'మార్కెట్ లైవ్ క్యూ',
    nav_display_screen: 'మార్కెట్ టీవీ డిస్ప్లే',
    nav_analytics: 'విశ్లేషణలు',
    nav_admin_panel: 'సూపర్ అడ్మిన్',
    nav_officer_portal: 'అధికారి పోర్టల్',
    nav_profile: 'నా ప్రొఫైల్',
    nav_login: 'లాగిన్',
    nav_logout: 'లాగౌట్',
    cta_book_now: 'సేకరణ స్లాట్ బుక్ చేయండి',
    cta_check_token: 'టోకెన్ ట్రాక్ చేయండి',
    cta_ai_help: 'AI వాయిస్ సహాయకుడు',
    hero_title: 'వేచి ఉండే సమయం లేకుండా కనీస మద్దతు ధరల సేకరణ.',
    hero_subtitle: 'రైతుల కోసం స్మార్ట్ స్లాట్ రిజర్వేషన్ మరియు లైవ్ క్యూ వ్యవస్థ.',
    live_msp_rates: 'నేటి ప్రభుత్వ కనీస మద్దతు ధరలు (MSP)',
    quintal: 'క్వింటాల్',
    per_quintal: 'క్వింటాల్‌కు',
    price_trends_title: 'ధరల ధోరణి & మద్దతు ధర (MSP) పోలిక',
    price_trends_subtitle: '7 రోజుల వ్యవసాయ మార్కెట్ ధరలు vs ప్రభుత్వ కనీస మద్దతు ధర',
    mandi_market_rate: 'ప్రస్తుత మార్కెట్ ధర',
    govt_msp_floor: 'ప్రభుత్వ MSP ధర',
    net_premium: 'రైతు ప్రీమియం',
    weekly_range: '7 రోజుల ధరల శ్రేణి',
    msp_assured_badge: '100% MSP గ్యారెంటీ',
    benchmark_feed: 'ధృవీకరించబడిన APMC మార్కెట్ ఫీడ్',
    status_booked: 'స్లాట్ బుక్ అయింది',
    status_checked_in: 'గేట్ వద్ద హాజరు',
    status_called: 'పిలువబడింది',
    status_quality: 'నాణ్యతా పరీక్ష',
    status_weighing: 'తూకం వేదిక',
    status_unloading: 'అన్‌లోడింగ్ ప్రాంతం',
    status_procured: 'సేకరణ పూర్తయింది',
    step_crop_details: '1. పంట వివరాలు',
    step_centre_select: '2. కేంద్రాన్ని ఎంచుకోండి',
    step_slot_time: '3. సమయ స్లాట్ ఎంచుకోండి',
    btn_confirm_booking: 'స్లాట్ ఖరారు చేయండి',
    btn_call_next: 'తదుపరి వాహనం పిలవండి',
    btn_check_in: 'గేట్ చెక్-ఇన్',
    token_label: 'టోకెన్ సంఖ్య',
    wait_time_label: 'అంచనా సమయం',
    vehicles_ahead: 'క్యూలో ముందున్న వాహనాలు',
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('kisansetu_lang') || 'en');

  const setLanguage = (code) => {
    setLang(code);
    localStorage.setItem('kisansetu_lang', code);
  };

  const t = (key) => {
    return TRANSLATIONS[lang]?.[key] || TRANSLATIONS.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLanguage, t, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
